kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${block_volume_name}
  annotations:
    volume.beta.kubernetes.io/oci-volume-source: ${block_volume_id}
spec:
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: ${availablity_domain_name}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${block_volume_size}Gi