apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-custom-storageclass
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  csi.storage.k8s.io/fstype: ${fs_type}
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer